import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "All Maps — MECCHA CHAMELEON Map Guide",
  description: "Complete map guide for MECCHA CHAMELEON. Find the best hiding spots for every official map with screenshots, difficulty ratings, and strategies.",
  keywords: [
    "meccha chameleon maps",
    "meccha chameleon all maps",
    "meccha chameleon map guide",
    "meccha chameleon map list",
    "meccha chameleon official maps",
    "meccha chameleon sewer",
    "meccha chameleon backrooms",
    "meccha chameleon map hiding spots",
    "meccha chameleon sewer hiding spots",
    "meccha chameleon backrooms hiding spots",
    "meccha chameleon map list 2026",
    "meccha chameleon map rotation",
    "meccha chameleon best maps",
    "meccha chameleon worst maps",
    "meccha chameleon map tier list",
    "meccha chameleon map rankings",
    "meccha chameleon sewer guide",
    "meccha chameleon backrooms guide",
    "meccha chameleon map strategies",
    "meccha chameleon map walkthrough",
    "meccha chameleon map overview",
    "meccha chameleon map selection",
    "meccha chameleon which map",
    "meccha chameleon best map for beginners",
    "meccha chameleon easiest map",
    "meccha chameleon hardest map",
    "meccha chameleon map difficulty",
    "meccha chameleon map spots",
    "meccha chameleon hiding spots per map",
    "meccha chameleon map by map",
    "meccha chameleon complete map guide",
    "meccha chameleon every map",
    "meccha chameleon map tips",
    "meccha chameleon map tricks",
    "meccha chameleon map secrets",
    "meccha chameleon map easter eggs",
    "meccha chameleon sewer tips",
    "meccha chameleon backrooms tips",
    "meccha chameleon sewer secrets",
    "meccha chameleon backrooms secrets",
    "meccha chameleon sewer best spots",
    "meccha chameleon backrooms best spots",
    "meccha chameleon map screenshots",
    "meccha chameleon map layouts",
    "meccha chameleon map locations",
    "meccha chameleon map spawn points",
    "meccha chameleon map guide 2026",
    "meccha chameleon updated maps",
    "meccha chameleon new maps",
  ],
  alternates: {
    canonical: "https://mecchachameleonlab.com/maps",
  },
  openGraph: {
    title: "All Maps | MECCHA CHAMELEON Guide",
    description: "Complete map guide for MECCHA CHAMELEON. Find the best hiding spots for every official map.",
    url: "https://mecchachameleonlab.com/maps",
    type: "website",
  },
};

export default function MapsLayout({ children }: { children: React.ReactNode }) {
  return children;
}
